feat: standardize ci (#279)
* standardize ci

* remove make proto from codeql job

* remove make proto from codeql job

* add job for testing go modules up to date

diff --git a/.github/workflows/release_rc.yml b/.github/workflows/release_rc.yml
--- a/.github/workflows/release_rc.yml
+++ b/.github/workflows/release_rc.yml
@@ -1,15 +1,42 @@
 name: Release Armada Operator - RC
 
 on:
-  push:
+  workflow_run:
+    types: [completed]
+    workflows: [CI]
     branches:
       - main
-      - master
 
 permissions:
   contents: write
 
 jobs:
+  validate:
+    if: github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success' && github.repository_owner == 'armadaproject'
+    name: "Validate revision"
+    runs-on: ubuntu-22.04
+
+    steps:
+      - name: "Checkout"
+        uses: "actions/checkout@v3"
+        with:
+          fetch-depth: 0
+
+      # The given ref should belong to the main branch.
+      # If it's main, it shouldn't be more than 2 commits away (in case another push happened in the meantime).
+      # Anything else is invalid.
+      - name: Validate ref
+        run: |
+          ref='${{ github.event.workflow_run.head_branch }}'
+          sha='${{ github.event.workflow_run.head_sha }}'
+
+          [ "$ref" == "main" ] &&
+          [ $(git branch --contains=$sha main | wc -l) -eq 1 ] &&
+          [ $(git rev-list --count $sha..main) -le 2 ]
+          if [ $? -ne 0 ]; then
+            echo "::error ::Invalid ref $ref $sha: must be a merge to main branch and not more than 2 commits away"
+            exit 1
+          fi
   release:
     name: Release
     runs-on: "ubuntu-22.04"
